// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZRrb9I11CgQu_ZomqzWL_aSRRSxBD2gs',
    appId: '1:395139449363:web:84ab8a7506f557e84675e6',
    messagingSenderId: '395139449363',
    projectId: 'noteflow-b54a6',
    authDomain: 'noteflow-b54a6.firebaseapp.com',
    storageBucket: 'noteflow-b54a6.firebasestorage.app',
    measurementId: 'G-NETVGY74BL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4FU6coC4-6I_-ZU32JpHiMEGOmMqgdtU',
    appId: '1:395139449363:android:afb904ef25cebf974675e6',
    messagingSenderId: '395139449363',
    projectId: 'noteflow-b54a6',
    storageBucket: 'noteflow-b54a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZvYOvsafQiv6CCY4ePenqE8_6dKln2Jk',
    appId: '1:395139449363:ios:811ac8e2c0ee074c4675e6',
    messagingSenderId: '395139449363',
    projectId: 'noteflow-b54a6',
    storageBucket: 'noteflow-b54a6.firebasestorage.app',
    iosBundleId: 'com.example.noteflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZvYOvsafQiv6CCY4ePenqE8_6dKln2Jk',
    appId: '1:395139449363:ios:811ac8e2c0ee074c4675e6',
    messagingSenderId: '395139449363',
    projectId: 'noteflow-b54a6',
    storageBucket: 'noteflow-b54a6.firebasestorage.app',
    iosBundleId: 'com.example.noteflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZRrb9I11CgQu_ZomqzWL_aSRRSxBD2gs',
    appId: '1:395139449363:web:95627d74015ed2874675e6',
    messagingSenderId: '395139449363',
    projectId: 'noteflow-b54a6',
    authDomain: 'noteflow-b54a6.firebaseapp.com',
    storageBucket: 'noteflow-b54a6.firebasestorage.app',
    measurementId: 'G-K76QTBFQ20',
  );
}
